In [1]:
## Script to generate randomized txt files for Catch the critter - Long experiment

In [2]:
# Create a txt file with tab delimited numbers as follows (36 long, 0's for random trials)
# targetID1 targetID2 xloc1 yloc1 xloc2 yloc2 delay1 delay2
# target ID can be 1,2,3
# x, y random pick between 100-400 [check this with presentation script], balanced by visual field (also within a trial one on each side)
# delay can be 2000, 3200, 5000, needs to be balanced

In [3]:
import numpy as np
import pandas as pd

paramNum = '20'

In [4]:
# Pixel value range
x = [100, 350]


# Set up coordinates and balance
balanceLR = np.array([1,1,1,1,1,1, -1,-1,-1,-1,-1,-1,])
balanceHL1 = np.array([1,1,1,1,1,1, -1,-1,-1,-1,-1,-1])
balanceHL2 = np.array([1,1,1,1,1,1, -1,-1,-1,-1,-1,-1])

np.random.shuffle(balanceLR)
np.random.shuffle(balanceHL1)
np.random.shuffle(balanceHL2)

balanceLR1 = balanceLR
balanceLR2 = -1*balanceLR

# draw random values 
randX1 = np.around((np.random.rand(12)*(x[1]-x[0]) + x[0])*balanceLR1, decimals = 0)
randX2 = np.around((np.random.rand(12)*(x[1]-x[0]) + x[0])*balanceLR2, decimals = 0)
randY1 = np.around((np.random.rand(12)*(x[1]))*balanceHL1, decimals = 0)
randY2 = np.around((np.random.rand(12)*(x[1]))*balanceHL2, decimals = 0)

In [5]:
# Target identity
tmpID = np.matrix('1,2; 1, 3; 1,4 ; 2, 1; 2, 3; 2, 4; 3, 1; 3, 2; 3, 4; 4, 1; 4, 2; 4, 3')
targetID = tmpID#np.tile(tmpID, (2,1)) # 24 total

#Set up delays matrix and randomize
tmpD = np.matrix('2000, 3200')
delays = np.repeat(tmpD, 12, axis = 0)

rng_state = np.random.get_state()
np.random.shuffle(delays)
np.random.set_state(rng_state)
np.random.shuffle(targetID) # not really relevant anymore but leaving it in in case we change the time-windows again
#np.random.shuffle(delays)
#np.random.shuffle(targetID)


In [6]:
targetID

matrix([[1, 4],
        [4, 2],
        [2, 4],
        [2, 1],
        [3, 2],
        [3, 4],
        [4, 3],
        [1, 2],
        [2, 3],
        [4, 1],
        [3, 1],
        [1, 3]])

In [7]:
# Generate random vs predictable trials

randScenes = np.array([0,1])
randScenes = np.repeat(randScenes, 12)
np.random.shuffle(randScenes)

In [8]:
randScenes

array([1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0])

In [9]:
# generate final matrix
num = 0
trialInfo = np.zeros((24, 8))
for i in range(24):
    if randScenes[i]:
        trialInfo[i, 0] = targetID[num, 0]
        trialInfo[i, 1] = targetID[num, 1]
        trialInfo[i, 2] = randX1[num]
        trialInfo[i, 3] = randY1[num]
        trialInfo[i, 4] = randX2[num]
        trialInfo[i, 5] = randY2[num]
        trialInfo[i, 6] = delays[num, 0]
        trialInfo[i, 7] = delays[num, 1]
        num += 1
#np.around(trialInfo, decimals = 0)
trialInfo.astype(int)
print(trialInfo.astype(int))


[[   1    4  194 -143 -341  184 2000 3200]
 [   4    2 -312   59  136  -50 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   2    4 -164    7  140  292 2000 3200]
 [   2    1  107 -214 -126  233 2000 3200]
 [   3    2 -320  -93  298  -30 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   3    4  227 -161 -221  307 2000 3200]
 [   4    3 -233   79  220  299 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   1    2  128 -290 -102  -76 2000 3200]
 [   2    3 -110  103  331 -249 2000 3200]
 [   4    1  189  268 -334  124 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   3    1 -297  156  136  -27 2000 3200]
 [   1    3  149 -138 -172 -340 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0

In [10]:
# save file

np.savetxt('targetParamsP' + paramNum + '.txt', trialInfo, delimiter = '\t', fmt = '%i')

In [11]:
# Create random scene parameter entries: 
randN = 8 # Number of blocks (always do more than you plan to use) Note to update .txt files when changing block size!
trialRand = np.zeros((randN*12, 8))
num2 = 0

targetRand = targetID

for j in range(randN):
    # Produce randomized targets and coordinates
    np.random.shuffle(balanceLR)
    np.random.shuffle(balanceHL1)
    np.random.shuffle(balanceHL2)

    balanceLR1 = balanceLR
    balanceLR2 = -1*balanceLR

    # draw random values 
    randX1r = np.around((np.random.rand(12)*(x[1]-x[0]) + x[0])*balanceLR1, decimals = 0)
    randX2r = np.around((np.random.rand(12)*(x[1]-x[0]) + x[0])*balanceLR2, decimals = 0)
    randY1r = np.around((np.random.rand(12)*(x[1]) )*balanceHL1, decimals = 0)
    randY2r = np.around((np.random.rand(12)*(x[1]) )*balanceHL2, decimals = 0)
    
    np.random.shuffle(targetRand)
    
    for k in range(12): 
        trialRand[num2,0] = targetRand[k,0]
        trialRand[num2,1] = targetRand[k,1]
        trialRand[num2,2] = randX1r[k]
        trialRand[num2,3] = randY1r[k]
        trialRand[num2,4] = randX2r[k]
        trialRand[num2,5] = randY2r[k]
        trialRand[num2,6] = delays[k,0]
        trialRand[num2,7] = delays[k,1]
        num2 += 1
        
trialRand.astype(int)
print(trialRand.astype(int))

[[   2    1 -179  326  341  271 2000 3200]
 [   2    3  225 -211 -201  290 2000 3200]
 [   4    1  236   -5 -134  133 2000 3200]
 [   3    4  142  127 -265  -57 2000 3200]
 [   3    1 -175 -343  161  261 2000 3200]
 [   3    2  347  103 -336 -333 2000 3200]
 [   4    3 -247 -330  262  -62 2000 3200]
 [   4    2 -346 -337  319 -230 2000 3200]
 [   2    4 -281  157  150  -61 2000 3200]
 [   1    3  273   67 -277 -271 2000 3200]
 [   1    4  293  268 -120  309 2000 3200]
 [   1    2 -222 -318  253  170 2000 3200]
 [   3    4  321 -322 -144  246 2000 3200]
 [   4    1  165 -123 -206 -115 2000 3200]
 [   3    1 -312  216  230 -252 2000 3200]
 [   2    1  277  318 -155  299 2000 3200]
 [   1    3 -200  -28  290 -309 2000 3200]
 [   2    4 -120 -127  324  296 2000 3200]
 [   4    3 -189  271  112 -206 2000 3200]
 [   2    3  303  330 -200  291 2000 3200]
 [   4    2  300  164 -212 -333 2000 3200]
 [   1    4 -279  326  158  197 2000 3200]
 [   3    2  111  -68 -284 -305 2000 3200]
 [   1    2

In [12]:
np.savetxt('targetRandParamsP'+ paramNum + '.txt', trialRand, delimiter = '\t', fmt = '%i')

In [13]:
num2

96

In [14]:
# Create random scene parameter entries: 
randN = 8 # Number of blocks (always do more than you plan to use) Note to update .txt files when changing block size!
trialRand = np.zeros((randN*12, 8))
num2 = 0

targetRand = targetID

for j in range(randN):
    # Produce randomized targets and coordinates
    np.random.shuffle(balanceLR)
    np.random.shuffle(balanceHL1)
    np.random.shuffle(balanceHL2)

    balanceLR1 = balanceLR
    balanceLR2 = -1*balanceLR

    # draw random values 
    randX1r = np.around((np.random.rand(12)*(x[1]-x[0]) + x[0])*balanceLR1, decimals = 0)
    randX2r = np.around((np.random.rand(12)*(x[1]-x[0]) + x[0])*balanceLR2, decimals = 0)
    randY1r = np.around((np.random.rand(12)*(x[1]) )*balanceHL1, decimals = 0)
    randY2r = np.around((np.random.rand(12)*(x[1]) )*balanceHL2, decimals = 0)
    
    np.random.shuffle(targetRand)
    
    for k in range(12): 
        trialRand[num2,0] = targetRand[k,0]
        trialRand[num2,1] = targetRand[k,1]
        trialRand[num2,2] = randX1r[k]
        trialRand[num2,3] = randY1r[k]
        trialRand[num2,4] = randX2r[k]
        trialRand[num2,5] = randY2r[k]
        trialRand[num2,6] = delays[k,0]
        trialRand[num2,7] = delays[k,1]
        num2 += 1
        
trialRand.astype(int)
print(trialRand.astype(int))

np.savetxt('targetRandParamsOP' + paramNum+ '.txt', trialRand, delimiter = '\t', fmt = '%i')

[[   2    4  252 -255 -289   46 2000 3200]
 [   2    1  206   64 -247 -323 2000 3200]
 [   3    1  309 -161 -244 -329 2000 3200]
 [   1    3  231  200 -151  198 2000 3200]
 [   1    2  255   17 -327 -337 2000 3200]
 [   4    3 -255 -263  257 -169 2000 3200]
 [   3    2 -260 -223  132  143 2000 3200]
 [   4    1 -238  202  305 -300 2000 3200]
 [   3    4  119  -15 -334  -72 2000 3200]
 [   1    4 -268 -125  206  309 2000 3200]
 [   2    3 -289  288  245  167 2000 3200]
 [   4    2 -175  197  240  341 2000 3200]
 [   4    1  148   12 -104  -63 2000 3200]
 [   3    4 -152 -148  334  331 2000 3200]
 [   2    3  121  -11 -270  257 2000 3200]
 [   1    3  107 -118 -259  269 2000 3200]
 [   2    1  184  280 -240  319 2000 3200]
 [   4    2  160 -135 -196 -228 2000 3200]
 [   1    2 -184 -102  215 -254 2000 3200]
 [   2    4 -237  190  145 -183 2000 3200]
 [   3    1 -124   95  152  158 2000 3200]
 [   1    4 -198  239  156   67 2000 3200]
 [   3    2  341  -68 -160 -115 2000 3200]
 [   4    3