In [1]:
## Script to generate randomized txt files for Catch the critter - Long experiment

In [51]:
# Create a txt file with tab delimited numbers as follows (36 long, 0's for random trials)
# targetID1 targetID2 xloc1 yloc1 xloc2 yloc2 delay1 delay2
# target ID can be 1,2,3
# x, y random pick between 100-400 [check this with presentation script], balanced by visual field (also within a trial one on each side)
# delay can be 2000, 3200, 5000, needs to be balanced

In [66]:
import numpy as np
import pandas as pd


In [67]:
# Pixel value range
x = [100, 400]


# Set up coordinates and balance
balanceLR = np.array([1,1,1,1,1,1,1,1,1, -1,-1,-1,-1,-1,-1,-1,-1, -1])
balanceHL1 = np.array([1,1,1,1,1,1,1,1,1, -1,-1,-1,-1,-1,-1,-1,-1, -1])
balanceHL2 = np.array([1,1,1,1,1,1,1,1,1, -1,-1,-1,-1,-1,-1,-1,-1, -1])

np.random.shuffle(balanceLR)
np.random.shuffle(balanceHL1)
np.random.shuffle(balanceHL2)

balanceLR1 = balanceLR
balanceLR2 = -1*balanceLR

# draw random values 
randX1 = np.around((np.random.rand(18)*(x[1]-x[0]) + x[0])*balanceLR1, decimals = 0)
randX2 = np.around((np.random.rand(18)*(x[1]-x[0]) + x[0])*balanceLR2, decimals = 0)
randY1 = np.around((np.random.rand(18)*(x[1]-x[0]) + x[0])*balanceHL1, decimals = 0)
randY2 = np.around((np.random.rand(18)*(x[1]-x[0]) + x[0])*balanceHL1, decimals = 0)

In [68]:
# Target identity
tmpID = np.matrix('1,2; 2, 3; 3, 1; 1, 3; 2, 1; 3, 2')
targetID = np.tile(tmpID, (3,1))

#Set up delays matrix and randomize
tmpD = np.matrix('2000, 3200; 2000, 5000; 3200, 5000')
delays = np.repeat(tmpD, 6, axis = 0)

rng_state = np.random.get_state()
np.random.shuffle(delays)
np.random.set_state(rng_state)
np.random.shuffle(targetID)
#np.random.shuffle(delays)
#np.random.shuffle(targetID)


In [69]:
targetID

matrix([[3, 2],
        [1, 3],
        [3, 1],
        [2, 3],
        [3, 1],
        [1, 3],
        [3, 2],
        [1, 2],
        [1, 3],
        [2, 1],
        [1, 2],
        [3, 1],
        [2, 3],
        [2, 1],
        [1, 2],
        [3, 2],
        [2, 3],
        [2, 1]])

In [70]:
# Generate random vs predictable trials

randScenes = np.array([0,1])
randScenes = np.repeat(randScenes, 18)
np.random.shuffle(randScenes)

In [71]:
# generate final matrix
num = 0
trialInfo = np.zeros((36, 8))
for i in range(36):
    if randScenes[i]:
        trialInfo[i, 0] = targetID[num, 0]
        trialInfo[i, 1] = targetID[num, 1]
        trialInfo[i, 2] = randX1[num]
        trialInfo[i, 3] = randY1[num]
        trialInfo[i, 4] = randX2[num]
        trialInfo[i, 5] = randY2[num]
        trialInfo[i, 6] = delays[num, 0]
        trialInfo[i, 7] = delays[num, 1]
        num += 1
#np.around(trialInfo, decimals = 0)
trialInfo.astype(int)
print(trialInfo.astype(int))


[[   3    2  210  314 -134  373 3200 5000]
 [   0    0    0    0    0    0    0    0]
 [   1    3 -337  335  131  376 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   3    1 -227 -285  231 -122 3200 5000]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   2    3  126 -391 -261 -191 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   3    1  323  257 -130  399 2000 5000]
 [   1    3 -268 -240  179 -106 3200 5000]
 [   3    2  162  173 -221  234 2000 5000]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   1    2  218 -114 -127 -265 2000 5000]
 [   1    3 -327 -368  197 -295 2000 5000]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   2    1  276  340 -316  319 2000 5000]
 [   0    0    0    0    0    0    0    0]
 [   1    2 -346 -274  104 -244 2000 3200]
 [   3    1 -122 -236  396 -290 2000 3200]
 [   0    0

In [72]:
# save file

np.savetxt('targetParams25.txt', trialInfo, delimiter = '\t', fmt = '%i')

In [41]:
trlInfo

NameError: name 'trlInfo' is not defined