In [1]:
## Script to generate randomized txt files for Catch the critter - Long experiment

In [2]:
# Create a txt file with tab delimited numbers as follows (36 long, 0's for random trials)
# targetID1 targetID2 xloc1 yloc1 xloc2 yloc2 delay1 delay2
# target ID can be 1,2,3
# x, y random pick between 100-400 [check this with presentation script], balanced by visual field (also within a trial one on each side)
# delay can be 2000, 3200, 5000, needs to be balanced

In [3]:
import numpy as np
import pandas as pd


In [4]:
# Pixel value range
x = [100, 350]


# Set up coordinates and balance
balanceLR = np.array([1,1,1,1,1,1,1,1,1,1,1,1, -1,-1,-1,-1,-1,-1,-1,-1, -1, -1, -1, -1])
balanceHL1 = np.array([1,1,1,1,1,1,1,1,1,1,1,1, -1,-1,-1,-1,-1,-1,-1,-1, -1, -1, -1, -1])
balanceHL2 = np.array([1,1,1,1,1,1,1,1,1,1,1,1, -1,-1,-1,-1,-1,-1,-1,-1, -1, -1, -1, -1])

np.random.shuffle(balanceLR)
np.random.shuffle(balanceHL1)
np.random.shuffle(balanceHL2)

balanceLR1 = balanceLR
balanceLR2 = -1*balanceLR

# draw random values 
randX1 = np.around((np.random.rand(24)*(x[1]-x[0]) + x[0])*balanceLR1, decimals = 0)
randX2 = np.around((np.random.rand(24)*(x[1]-x[0]) + x[0])*balanceLR2, decimals = 0)
randY1 = np.around((np.random.rand(24)*(x[1]-x[0]) + x[0])*balanceHL1, decimals = 0)
randY2 = np.around((np.random.rand(24)*(x[1]-x[0]) + x[0])*balanceHL2, decimals = 0)

In [5]:
# Target identity
tmpID = np.matrix('1,2; 1, 3; 1,4 ; 2, 1; 2, 3; 2, 4; 3, 1; 3, 2;, 3, 4; 4, 1; 4, 2; 4, 3')
targetID = np.tile(tmpID, (2,1)) # 24 total

#Set up delays matrix and randomize
tmpD = np.matrix('2000, 3200')
delays = np.repeat(tmpD, 24, axis = 0)

rng_state = np.random.get_state()
np.random.shuffle(delays)
np.random.set_state(rng_state)
np.random.shuffle(targetID) # not really relevant anymore but leaving it in in case we change the time-windows again
#np.random.shuffle(delays)
#np.random.shuffle(targetID)


In [6]:
targetID

matrix([[1, 3],
        [3, 1],
        [4, 2],
        [3, 1],
        [2, 3],
        [4, 1],
        [4, 1],
        [3, 2],
        [1, 2],
        [1, 4],
        [2, 4],
        [1, 2],
        [4, 3],
        [2, 1],
        [1, 3],
        [2, 4],
        [4, 3],
        [4, 2],
        [3, 4],
        [2, 3],
        [1, 4],
        [3, 4],
        [2, 1],
        [3, 2]])

In [7]:
# Generate random vs predictable trials

randScenes = np.array([0,1])
randScenes = np.repeat(randScenes, 24)
np.random.shuffle(randScenes)

In [8]:
# generate final matrix
num = 0
trialInfo = np.zeros((48, 8))
for i in range(48):
    if randScenes[i]:
        trialInfo[i, 0] = targetID[num, 0]
        trialInfo[i, 1] = targetID[num, 1]
        trialInfo[i, 2] = randX1[num]
        trialInfo[i, 3] = randY1[num]
        trialInfo[i, 4] = randX2[num]
        trialInfo[i, 5] = randY2[num]
        trialInfo[i, 6] = delays[num, 0]
        trialInfo[i, 7] = delays[num, 1]
        num += 1
#np.around(trialInfo, decimals = 0)
trialInfo.astype(int)
print(trialInfo.astype(int))


[[   0    0    0    0    0    0    0    0]
 [   1    3  259 -162 -309  334 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   3    1 -163 -307  130  180 2000 3200]
 [   4    2 -172  175  156  302 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   3    1  234  345 -270  127 2000 3200]
 [   2    3 -107  263  151 -163 2000 3200]
 [   4    1 -207 -177  117 -133 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   4    1 -331  338  224  174 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   3    2 -127  219  133  284 2000 3200]
 [   1    2  293  219 -101  229 2000 3200]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   0    0    0    0    0    0    0    0]
 [   1    4  158  183 -312  104 2000 3200]
 [   2    4  257  330 -332 -281 2000 3200]
 [   1    2  118  117 -205  343 2000 3200]
 [   4    3 -268  243  247 -131 2000 3200]
 [   0    0

In [9]:
# save file

np.savetxt('4targetParams20.txt', trialInfo, delimiter = '\t', fmt = '%i')

In [10]:
trialInfo.shape

(48, 8)

In [11]:
num

24